include: package:flutter_lints/flutter.yaml

linter:
  rules:

    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_returning_null_for_void: true
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    avoid_redundant_argument_values: true
    depend_on_referenced_packages: true
    always_put_required_named_parameters_first: true
    prefer_const_constructors_in_immutables: true
    avoid_types_as_parameter_names: true
    annotate_overrides: true
    unnecessary_overrides: true
    avoid_renaming_method_parameters: true
    prefer_expression_function_bodies: true

    language:
      strict-casts: true
      strict-inference: true
      strict-raw-types: true

    errors:
      close_sinks: ignore
      missing_required_param: error
      missing_return: error

    exclude:
      - test/.test_coverage.dart
      - lib/generated_plugin_registrant.dart