include: package:flutter_lints/flutter.yaml

linter:
  rules:

    # ðŸ’¡ Ù‚ÙˆØ§Ø¹Ø¯ Dart Ø¹Ø§Ù…Ø©
    always_declare_return_types: true        # Ø§Ø¬Ø¨Ø± Ø§Ù„Ù…Ø·ÙˆØ± ÙŠØ­Ø¯Ø¯ Ù†ÙˆØ¹ Ø§Ù„Ù‚ÙŠÙ…Ø© Ø§Ù„Ù…Ø±Ø¬Ø¹Ø© Ù…Ù† Ø§Ù„Ø¯ÙˆØ§Ù„
    avoid_print: true                         # ÙŠÙ…Ù†Ø¹ Ø§Ø³ØªØ®Ø¯Ø§Ù… print() ÙˆÙŠÙØ¶Ù‘Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… Logger
    avoid_unnecessary_containers: true        # ÙŠÙ…Ù†Ø¹ Ø§Ø³ØªØ®Ø¯Ø§Ù… Container Ø¥Ø°Ø§ Ù…Ø§ Ù„Ù‡ ÙØ§Ø¦Ø¯Ø© ÙˆØ§Ø¶Ø­Ø©
    avoid_empty_else: true                    # ÙŠÙ…Ù†Ø¹ ØªØ±Ùƒ else ÙØ§Ø¶ÙŠØ© Ø¨Ø¯ÙˆÙ† Ø£ÙŠ ÙƒÙˆØ¯
    avoid_init_to_null: true                  # ÙŠÙ…Ù†Ø¹ ØªÙ‡ÙŠØ¦Ø© Ø§Ù„Ù…ØªØºÙŠØ±Ø§Øª Ø¨Ù€ null Ù„Ø£Ù† Dart ØªØ¹Ù…Ù„Ù‡Ø§ ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‹Ø§
    avoid_returning_null_for_void: true       # Ù„Ø§ ØªØ±Ø¬Ø¹ null ÙÙŠ Ø¯ÙˆØ§Ù„ void
    curly_braces_in_flow_control_structures: true  # ÙŠÙØ±Ø¶ Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø§Ù„Ø£Ù‚ÙˆØ§Ø³ { } ÙÙŠ if / else / for Ø­ØªÙ‰ Ù„Ùˆ Ø³Ø·Ø± ÙˆØ§Ø­Ø¯
    prefer_const_constructors: true           # ÙŠÙØ¶Ù‘Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… const Ø¥Ø°Ø§ ÙƒØ§Ù† Ø§Ù„ÙƒØ§Ø¦Ù† Ø«Ø§Ø¨Øª
    prefer_const_literals_to_create_immutables: true  # ÙŠÙØ¶Ù‘Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… const Ù…Ø¹ Ø§Ù„Ù‚ÙˆØ§Ø¦Ù… ÙˆØ§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª Ø§Ù„Ø«Ø§Ø¨ØªØ©
    prefer_final_fields: true                 # ÙŠÙØ¶Ù‘Ù„ Ø¬Ø¹Ù„ Ø§Ù„Ù…ØªØºÙŠØ±Ø§Øª Ø¯Ø§Ø®Ù„ Ø§Ù„ÙƒÙ„Ø§Ø³ final Ø¥Ù† Ù„Ù… ØªØªØºÙŠØ±
    prefer_final_in_for_each: true            # ÙŠÙØ¶Ù‘Ù„ final ÙÙŠ Ø­Ù„Ù‚Ø§Øª forEach Ù„Ùˆ Ø§Ù„Ù‚ÙŠÙ…Ø© Ù…Ø§ ØªØªØºÙŠØ±
    prefer_final_locals: true                 # ÙŠÙØ¶Ù‘Ù„ final Ù„Ù„Ù…ØªØºÙŠØ±Ø§Øª Ø¯Ø§Ø®Ù„ Ø§Ù„Ø¯ÙˆØ§Ù„ Ø¥Ø°Ø§ Ù…Ø§ Ø±Ø§Ø­ ØªØªØºÙŠØ±
    prefer_single_quotes: true                # ÙŠÙØ¶Ù‘Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… ' Ø¨Ø¯Ù„Ø§Ù‹ Ù…Ù† " Ù…Ø§ Ù„Ù… ÙŠÙƒÙ† Ù‡Ù†Ø§Ùƒ Ø³Ø¨Ø¨ Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù… "
    unnecessary_this: true                    # ÙŠÙ…Ù†Ø¹ Ø§Ø³ØªØ®Ø¯Ø§Ù… this Ø¥Ø°Ø§ Ù„Ù… ÙŠÙƒÙ† Ù„Ù‡ Ø¯Ø§Ø¹Ù
    use_key_in_widget_constructors: true      # ÙŠØªØ£ÙƒØ¯ Ø£Ù†Ùƒ ØªØ¶ÙŠÙ Key ÙÙŠ Ø§Ù„ÙƒÙˆÙ†Ø³ØªØ±ÙƒØªØ± Ù„Ù„Ù€ Widgets Ø§Ù„Ù…Ø®ØµØµØ©
    sort_child_properties_last: true          # ÙŠØ·Ù„Ø¨ ØªØ±ØªÙŠØ¨ Ø®Ø§ØµÙŠØ© child ÙÙŠ Ø¢Ø®Ø± Ø®ØµØ§Ø¦Øµ Ø§Ù„Ù€ Widget
    sized_box_for_whitespace: true            # ÙŠÙØ¶Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… SizedBox Ø¨Ø¯Ù„ Containers ÙØ§Ø¶ÙŠØ© Ù„Ù…Ø³Ø§Ø­Ø§Øª Ø¨ÙŠØ¶Ø§Ø¡
    avoid_redundant_argument_values: true     # ÙŠÙ…Ù†Ø¹ ØªÙ…Ø±ÙŠØ± Ù‚ÙŠÙ… Ù‡ÙŠ Ù†ÙØ³Ù‡Ø§ Ø§Ù„Ù‚ÙŠÙ… Ø§Ù„Ø§ÙØªØ±Ø§Ø¶ÙŠØ©

    # ðŸ’¡ Ù‚ÙˆØ§Ø¹Ø¯ Flutter Ø®Ø§ØµØ©
    depend_on_referenced_packages: true       # ÙŠÙ…Ù†Ø¹ Ø§Ø³ØªØ®Ø¯Ø§Ù… Ù…ÙƒØªØ¨Ø§Øª Ù…Ø§ ØªÙ… Ø¥Ø¶Ø§ÙØªÙ‡Ø§ ÙÙŠ pubspec.yaml
    always_put_required_named_parameters_first: true  # ÙŠØ·Ù„Ø¨ ÙˆØ¶Ø¹ Ø§Ù„Ù…Ø¹Ø§Ù…Ù„Ø§Øª Ø§Ù„Ù…Ø·Ù„ÙˆØ¨Ø© Ø£ÙˆÙ„Ø§Ù‹ ÙÙŠ Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ù…Ø¹Ø§Ù…Ù„Ø§Øª
    prefer_const_constructors_in_immutables: true     # ÙŠÙØ¶Ù‘Ù„ Ø§Ø³ØªØ®Ø¯Ø§Ù… const ÙÙŠ Ø§Ù„ÙƒÙ„Ø§Ø³Ø§Øª ØºÙŠØ± Ø§Ù„Ù‚Ø§Ø¨Ù„Ø© Ù„Ù„ØªØºÙŠÙŠØ±
    avoid_types_as_parameter_names: true      # ÙŠÙ…Ù†Ø¹ Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø£Ø³Ù…Ø§Ø¡ Ø£Ù†ÙˆØ§Ø¹ ÙƒØ£Ø³Ù…Ø§Ø¡ Ù„Ù„Ù…Ø¹Ø§Ù…Ù„Ø§Øª (Ù…Ø«Ù„ String String)

    # ðŸ’¡ ØªØ­Ø³ÙŠÙ†Ø§Øª Ø¹Ù„Ù‰ ÙƒØªØ§Ø¨Ø© Ø§Ù„ÙƒÙˆØ¯
    annotate_overrides: true                  # ÙŠØ¬Ø¨Ø±Ùƒ ØªØ¶ÙŠÙ @override Ø¹Ù†Ø¯ Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹Ø±ÙŠÙ Ø¯ÙˆØ§Ù„
    unnecessary_overrides: true               # ÙŠÙ…Ù†Ø¹ Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹Ø±ÙŠÙ Ø¯ÙˆØ§Ù„ Ø¨Ø¯ÙˆÙ† Ø¥Ø¶Ø§ÙØ© Ø´ÙŠØ¡ Ø¬Ø¯ÙŠØ¯
    avoid_renaming_method_parameters: true    # ÙŠÙ…Ù†Ø¹ ØªØºÙŠÙŠØ± Ø£Ø³Ù…Ø§Ø¡ Ø§Ù„Ù…Ø¹Ø§Ù…Ù„Ø§Øª Ø¨Ø¯ÙˆÙ† Ø³Ø¨Ø¨ Ø¹Ù†Ø¯ Ø§Ù„ØªÙˆØ±ÙŠØ«
    prefer_expression_function_bodies: true   # ÙŠÙØ¶Ù„ ÙƒØªØ§Ø¨Ø© Ø§Ù„Ø¯ÙˆØ§Ù„ Ø§Ù„Ù‚ØµÙŠØ±Ø© ÙƒØ³Ø·Ø± ÙˆØ§Ø­Ø¯ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… =>
